image: node:10

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - install
  - validate
  - build

install:
  stage: install
  script: yarn

lint:
  stage: validate
  script: yarn lint

test:
  stage: validate
  script: yarn test

test_coverage:
  stage: build
  script: yarn test:coverage

storybook:
  stage: build
  script: yarn storybook:build
