workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always

default:
  image: node:lts
  before_script:
    - yarn --cache-folder .yarn
  cache: &cache
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .yarn
    policy: pull

stages:
  - setup
  - build
  - deploy

install:
  stage: setup
  script: echo "Done by the before script"
  cache:
    <<: *cache
    policy: pull-push

lint:
  stage: build
  script: "yarn ci:validate:lint"

test:
  stage: build
  script: "yarn ci:validate:test"
  artifacts:
    paths:
      - build/coverage

build:
  stage: build
  script: "yarn ci:build"
  artifacts:
    paths:
      - build/storybook

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  before_script: []
  cache: {}
  script:
    - "cp -r build/storybook/* public/"
    - "gzip -k -6 $(find public -type f -name '*.js')"
    - "gzip -k -6 $(find public -type f -name '*.css')"
    - "gzip -k -6 $(find public -type f -name '*.html')"
    - "gzip -k -6 $(find public -type f -name '*.svg')"
  artifacts:
    paths:
      - public
