image: node:10

stages:
  - setup
  - validate
  - build
  - post-validate

install:
  stage: setup
  script: yarn
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: push

lint-js:
  stage: validate
  before_script:
    - yarn
  script: yarn lint:js
  cache: &cache
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull

lint-css:
  stage: validate
  before_script:
    - yarn
  script: yarn lint:css
  cache: *cache

test:
  stage: validate
  before_script:
    - yarn
  script: yarn test
  cache: *cache

test_coverage:
  stage: build
  before_script:
    - yarn
  script: yarn test:coverage
  cache: *cache
  artifacts:
    paths:
      - build/coverage

storybook:
  stage: build
  before_script:
    - yarn
  script: yarn storybook:build
  cache: *cache
  artifacts:
    paths:
      - build/storybook

es-check:
  stage: post-validate
  before_script:
    - yarn
  script: yarn es-check
  cache: *cache
