image: node:10

stages:
  - setup
  - validate
  - build

install:
  stage: setup
  script: yarn
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: push

lint-js:
  stage: validate
  before_script:
    - yarn
  script: yarn lint:js
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull

lint-css:
  stage: validate
  before_script:
    - yarn
  script: yarn lint:css
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull

test:
  stage: validate
  before_script:
    - yarn
  script: yarn test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull

test_coverage:
  stage: build
  before_script:
    - yarn
  script: yarn test:coverage
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - build/coverage

storybook:
  stage: build
  before_script:
    - yarn
  script: yarn storybook:build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull
  artifacts:
    paths:
      - build/storybook
