name: Build

on:
  - push

env:
  CI: "true"

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: "node:lts"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: setup
        run: "yarn"
      - name: lint
        run: "yarn ci:validate:lint"
      - name: test
        run: "yarn ci:validate:test"

  build:
    needs: validate

    runs-on: ubuntu-latest
    container:
      image: "node:lts"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: setup
        run: "yarn"
      - name: build
        run: "yarn ci:build"
